/**
 * Demo Figma-like data for the interactive demo mode.
 * Mimics what the Figma API returns after analysis.
 */

export const DEMO_SCREENS = [
  {
    id: 'screen-login',
    name: 'Login Screen',
    pageName: 'Onboarding',
    width: 390,
    height: 844,
    score: 58,
    passed: 7,
    failed: 4,
    warnings: 1,
    checks: [
      {
        id: 'contrast-login-body',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Subtitle text',
        status: 'fail',
        severity: 'critical',
        ratio: '3.20:1',
        rawRatio: 3.2,
        textColor: '#9E9E9E',
        bgColor: '#FFFFFF',
        wcagLevel: 'FAIL',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: 'Darken the subtitle text from #9E9E9E to at least #767676 to achieve 4.5:1 contrast on a white background. Consider #595959 for more breathing room.',
        detail: 'Text "Sign in to continue" — 3.20:1 contrast ratio',
      },
      {
        id: 'contrast-login-placeholder',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Input placeholder',
        status: 'fail',
        severity: 'critical',
        ratio: '2.85:1',
        rawRatio: 2.85,
        textColor: '#BDBDBD',
        bgColor: '#FFFFFF',
        wcagLevel: 'FAIL',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: 'Placeholder text must also meet 4.5:1. Use #757575 or darker for placeholder on white. Note: placeholders should not replace visible labels.',
        detail: 'Text "Email address" — 2.85:1 contrast ratio',
      },
      {
        id: 'tap-login-forgot',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Forgot password link',
        status: 'fail',
        severity: 'critical',
        actual: '120×20pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: false,
        fix: 'The "Forgot password" link is only 20pt tall. Add at least 12pt of vertical padding (6pt top + 6pt bottom) to bring the touch area to 44pt. You can use padding without changing visual appearance.',
        detail: '"Forgot password?" — 120×20pt (min 44×44pt)',
      },
      {
        id: 'tap-login-social',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Sign in with Google',
        status: 'pass',
        severity: 'pass',
        actual: '358×52pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: '"Sign in with Google" — 358×52pt ✓',
      },
      {
        id: 'textsize-login-hint',
        type: 'text-size',
        label: 'Text Size',
        element: 'Helper text',
        status: 'fail',
        severity: 'critical',
        fontSize: '9pt',
        minRequired: '11pt',
        dynamicTypeReady: false,
        fix: 'Increase helper text from 9pt to at least 11pt (iOS minimum). For Dynamic Type support, consider 13pt or 14pt as a baseline, allowing it to scale further with user settings.',
        detail: '"Password must be 8+ characters" — 9pt (min 11pt)',
      },
      {
        id: 'textsize-login-label',
        type: 'text-size',
        label: 'Text Size',
        element: 'Input label',
        status: 'pass',
        severity: 'pass',
        fontSize: '14pt',
        minRequired: '11pt',
        dynamicTypeReady: false,
        fix: 'Consider using 16pt for better Dynamic Type baseline. Current 14pt may cause truncation at larger accessibility sizes.',
        detail: '"Email" label — 14pt',
      },
      {
        id: 'contrast-login-cta',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Primary CTA text',
        status: 'pass',
        severity: 'pass',
        ratio: '7.42:1',
        rawRatio: 7.42,
        textColor: '#FFFFFF',
        bgColor: '#1565C0',
        wcagLevel: 'AAA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: 'Text "Sign In" — 7.42:1 contrast ratio (AAA)',
      },
      {
        id: 'contrast-login-heading',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Page heading',
        status: 'pass',
        severity: 'pass',
        ratio: '18.10:1',
        rawRatio: 18.1,
        textColor: '#212121',
        bgColor: '#FFFFFF',
        wcagLevel: 'AAA',
        isLargeText: true,
        threshold: '3:1 (large text)',
        fix: null,
        detail: 'Text "Welcome back" — 18.10:1 contrast ratio (AAA)',
      },
      {
        id: 'textsize-login-terms',
        type: 'text-size',
        label: 'Text Size',
        element: 'Terms & Privacy link',
        status: 'warning',
        severity: 'warning',
        fontSize: '11pt',
        minRequired: '11pt',
        dynamicTypeReady: false,
        fix: 'Text is at the minimum threshold (11pt). Consider 13pt for better readability and Dynamic Type support. Ensure the link text still meets tap target size requirements.',
        detail: '"Terms of Service" link — 11pt (at minimum)',
      },
      {
        id: 'tap-login-terms',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Terms link',
        status: 'pass',
        severity: 'pass',
        actual: '120×44pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: '"Terms of Service" — 120×44pt ✓',
      },
      {
        id: 'contrast-login-footer',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Footer text',
        status: 'pass',
        severity: 'pass',
        ratio: '5.80:1',
        rawRatio: 5.8,
        textColor: '#757575',
        bgColor: '#FFFFFF',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: 'Text "Don\'t have an account?" — 5.80:1 contrast ratio',
      },
      {
        id: 'textsize-login-body',
        type: 'text-size',
        label: 'Text Size',
        element: 'Body paragraph',
        status: 'pass',
        severity: 'pass',
        fontSize: '16pt',
        minRequired: '11pt',
        dynamicTypeReady: true,
        fix: null,
        detail: '"Body copy" — 16pt ✓ (Dynamic Type ready)',
      },
    ],
  },
  {
    id: 'screen-home',
    name: 'Home Feed',
    pageName: 'Main App',
    width: 390,
    height: 844,
    score: 82,
    passed: 9,
    failed: 1,
    warnings: 2,
    checks: [
      {
        id: 'contrast-home-card-text',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Card description',
        status: 'fail',
        severity: 'critical',
        ratio: '3.85:1',
        rawRatio: 3.85,
        textColor: '#AAAAAA',
        bgColor: '#F5F5F5',
        wcagLevel: 'FAIL',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: 'Use #767676 or darker for body text on the light card background (#F5F5F5). This achieves exactly 4.5:1 contrast. Try #595959 for comfortable reading with headroom.',
        detail: 'Text "Card description text" — 3.85:1 contrast ratio',
      },
      {
        id: 'tap-home-nav',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Bottom nav item',
        status: 'pass',
        severity: 'pass',
        actual: '78×56pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: 'Nav "Home" — 78×56pt ✓',
      },
      {
        id: 'tap-home-fab',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Floating action button',
        status: 'pass',
        severity: 'pass',
        actual: '56×56pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: 'FAB "Create" — 56×56pt ✓',
      },
      {
        id: 'tap-home-icon-share',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Share icon button',
        status: 'warning',
        severity: 'warning',
        actual: '44×36pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: false,
        fix: 'The share icon button height is 36pt, just below the 44pt minimum. Add 4pt vertical padding to the icon button wrapper to meet guidelines without changing visual design.',
        detail: '"Share" icon — 44×36pt (height borderline)',
      },
      {
        id: 'textsize-home-caption',
        type: 'text-size',
        label: 'Text Size',
        element: 'Card timestamp',
        status: 'warning',
        severity: 'warning',
        fontSize: '11pt',
        minRequired: '11pt',
        dynamicTypeReady: false,
        fix: 'At exactly 11pt, this is at the minimum. If this text is important (timestamps, metadata), consider 12–13pt so it remains readable when Dynamic Type is enabled.',
        detail: '"2 hours ago" timestamp — 11pt (at minimum)',
      },
      {
        id: 'contrast-home-heading',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Section heading',
        status: 'pass',
        severity: 'pass',
        ratio: '15.30:1',
        rawRatio: 15.3,
        textColor: '#111111',
        bgColor: '#FFFFFF',
        wcagLevel: 'AAA',
        isLargeText: true,
        threshold: '3:1 (large text)',
        fix: null,
        detail: 'Text "Featured" — 15.30:1 contrast ratio (AAA)',
      },
      {
        id: 'contrast-home-badge',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Status badge text',
        status: 'pass',
        severity: 'pass',
        ratio: '5.20:1',
        rawRatio: 5.2,
        textColor: '#1B5E20',
        bgColor: '#E8F5E9',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: 'Badge "Active" — 5.20:1 contrast ratio',
      },
      {
        id: 'textsize-home-body',
        type: 'text-size',
        label: 'Text Size',
        element: 'Card body text',
        status: 'pass',
        severity: 'pass',
        fontSize: '15pt',
        minRequired: '11pt',
        dynamicTypeReady: true,
        fix: null,
        detail: '"Card body content" — 15pt ✓',
      },
      {
        id: 'tap-home-card',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Content card',
        status: 'pass',
        severity: 'pass',
        actual: '358×120pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: 'Content card — 358×120pt ✓',
      },
      {
        id: 'contrast-home-link',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Inline link text',
        status: 'pass',
        severity: 'pass',
        ratio: '5.92:1',
        rawRatio: 5.92,
        textColor: '#1565C0',
        bgColor: '#FFFFFF',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: 'Link "Read more" — 5.92:1 contrast ratio',
      },
      {
        id: 'textsize-home-heading',
        type: 'text-size',
        label: 'Text Size',
        element: 'Page title',
        status: 'pass',
        severity: 'pass',
        fontSize: '24pt',
        minRequired: '11pt',
        dynamicTypeReady: true,
        fix: null,
        detail: '"For You" heading — 24pt ✓ (Dynamic Type ready)',
      },
      {
        id: 'tap-home-avatar',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Avatar / profile link',
        status: 'pass',
        severity: 'pass',
        actual: '44×44pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: 'Avatar — 44×44pt ✓ (exactly at minimum)',
      },
    ],
  },
  {
    id: 'screen-settings',
    name: 'Settings',
    pageName: 'Main App',
    width: 390,
    height: 844,
    score: 94,
    passed: 11,
    failed: 0,
    warnings: 1,
    checks: [
      {
        id: 'contrast-settings-label',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Setting label',
        status: 'pass',
        severity: 'pass',
        ratio: '12.60:1',
        rawRatio: 12.6,
        textColor: '#212121',
        bgColor: '#FFFFFF',
        wcagLevel: 'AAA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: '"Notifications" label — 12.60:1 contrast ratio',
      },
      {
        id: 'contrast-settings-secondary',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Secondary description',
        status: 'pass',
        severity: 'pass',
        ratio: '5.74:1',
        rawRatio: 5.74,
        textColor: '#616161',
        bgColor: '#FFFFFF',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: 'Description "Push, Email, SMS" — 5.74:1',
      },
      {
        id: 'tap-settings-toggle',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Toggle switch',
        status: 'pass',
        severity: 'pass',
        actual: '51×31pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: false,
        fix: null,
        detail: 'Toggle — 51×31pt (extended hit area ✓)',
      },
      {
        id: 'tap-settings-row',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Settings row',
        status: 'pass',
        severity: 'pass',
        actual: '358×56pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: 'Settings row — 358×56pt ✓',
      },
      {
        id: 'textsize-settings-desc',
        type: 'text-size',
        label: 'Text Size',
        element: 'Description text',
        status: 'warning',
        severity: 'warning',
        fontSize: '12pt',
        minRequired: '11pt',
        dynamicTypeReady: false,
        fix: 'Description text at 12pt passes the minimum but may be hard to read. Consider 13–14pt for better readability across Dynamic Type sizes.',
        detail: 'Description "Manage notifications" — 12pt',
      },
      {
        id: 'contrast-settings-danger',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Delete account button',
        status: 'pass',
        severity: 'pass',
        ratio: '5.80:1',
        rawRatio: 5.8,
        textColor: '#C62828',
        bgColor: '#FFFFFF',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: '"Delete Account" — 5.80:1 contrast ratio',
      },
      {
        id: 'textsize-settings-heading',
        type: 'text-size',
        label: 'Text Size',
        element: 'Section heading',
        status: 'pass',
        severity: 'pass',
        fontSize: '17pt',
        minRequired: '11pt',
        dynamicTypeReady: true,
        fix: null,
        detail: '"Account" section — 17pt ✓',
      },
      {
        id: 'tap-settings-avatar',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'Profile avatar',
        status: 'pass',
        severity: 'pass',
        actual: '72×72pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: 'Avatar — 72×72pt ✓',
      },
      {
        id: 'contrast-settings-icon',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Section icon',
        status: 'pass',
        severity: 'pass',
        ratio: '4.60:1',
        rawRatio: 4.6,
        textColor: '#757575',
        bgColor: '#FFFFFF',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: 'Settings icon — 4.60:1 contrast ratio',
      },
      {
        id: 'textsize-settings-label',
        type: 'text-size',
        label: 'Text Size',
        element: 'Row label',
        status: 'pass',
        severity: 'pass',
        fontSize: '16pt',
        minRequired: '11pt',
        dynamicTypeReady: true,
        fix: null,
        detail: '"Notifications" row label — 16pt ✓',
      },
      {
        id: 'tap-settings-link',
        type: 'tap-target',
        label: 'Tap Target Size',
        element: 'External link',
        status: 'pass',
        severity: 'pass',
        actual: '358×44pt',
        recommended: '44×44pt minimum',
        widthPass: true,
        heightPass: true,
        fix: null,
        detail: '"Privacy Policy" link — 358×44pt ✓',
      },
      {
        id: 'contrast-settings-version',
        type: 'contrast',
        label: 'Color Contrast',
        element: 'Version number',
        status: 'pass',
        severity: 'pass',
        ratio: '4.82:1',
        rawRatio: 4.82,
        textColor: '#717171',
        bgColor: '#FFFFFF',
        wcagLevel: 'AA',
        isLargeText: false,
        threshold: '4.5:1 (normal text)',
        fix: null,
        detail: '"v2.4.1" — 4.82:1 contrast ratio',
      },
    ],
  },
]
